"""provider_settings api_key_hint

Revision ID: 7f1210931f08
Revises: c6b305320af5
Create Date: 2026-06-25 23:21:06.297947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1210931f08'
down_revision: Union[str, None] = 'c6b305320af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_settings', sa.Column('api_key_hint', sa.String(length=40), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_settings', 'api_key_hint')
    # ### end Alembic commands ###
